language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
script:
  - echo "no tests"
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-api-feed ose4g/udagram-api-feed:v1
  - docker tag udagram-api-user ose4g/udagram-api-user:v1
  - docker tag udagram-frontend ose4g/udagram-frontend:v1
  - docker tag reverseproxy ose4g/reverseproxy:v1


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ose4g/udagram-api-feed:v1
  - docker push ose4g/udagram-api-user:v1
  - docker push ose4g/udagram-frontend:v1
  - docker push ose4g/reverseproxy:v1