version: "3"
services:
  reverseproxy:
      image: messayed/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: messayed/udagram-api-user
    environment:
      POSTGRES_USERNAME: process.env.POSTGRES_USERNAME
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD 
      POSTGRES_DB: process.env.POSTGRES_DB 
      POSTGRES_HOST: process.env.POSTGRES_HOST
      AWS_REGION: process.env.AWS_REGION 
      AWS_PROFILE: process.env.AWS_PROFILE 
      AWS_BUCKET: process.env.AWS_BUCKET
      JWT_SECRET: process.env.JWT_SECRET
      URL: "http://localhost:8100"
  backend-feed:
    image: messayed/udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: process.env.POSTGRES_USERNAME
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD 
      POSTGRES_DB: process.env.POSTGRES_DB
      POSTGRES_HOST: process.env.POSTGRES_HOST
      AWS_REGION: process.env.AWS_REGION
      AWS_PROFILE: process.env.AWS_PROFILE 
      AWS_BUCKET: process.env.AWS_BUCKET
      JWT_SECRET: process.env.JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: messayed/udagram-frontend:local
    ports:
      - "8100:80"
